"use client";
import dynamic from "next/dynamic";
import Image from "next/image";
import {ChangeEvent,FormEvent,useEffect,useMemo,useState} from "react";
import {API_BASE_URL,MAX_PHOTO_BYTES} from "@/lib/config";
import type {Point} from "@/components/FloodMap";
const FloodMap=dynamic(()=>import("@/components/FloodMap"),{ssr:false,loading:()=> <div className="map-loading">กำลังเปิดแผนที่...</div>});
type Verification="VERIFIED"|"PENDING_REVIEW"|"UNVERIFIED";
type Result={report_code:string;verification_status:Verification};
type FloodReportPayload={flood_latitude:number;flood_longitude:number;water_level_cm:number;road_status:string;vehicle_4w_status:string;vehicle_6w_status:string;vehicle_10w_status:string;description:string|null;reporter_latitude?:number;reporter_longitude?:number;reporter_gps_accuracy_m?:number};
const imageTypes=["image/jpeg","image/png","image/webp"];
const statusText:Record<Verification,{title:string;detail?:string}>={
 VERIFIED:{title:"ตรวจสอบตำแหน่งแล้ว",detail:"ตำแหน่งผู้แจ้งอยู่ใกล้กับจุดที่รายงานและมีรูปภาพประกอบ"},
 PENDING_REVIEW:{title:"รอตรวจสอบ"},UNVERIFIED:{title:"ยังไม่ได้ตรวจสอบ"}};
function distance(a:Point,b:Point){const r=6371000,p=Math.PI/180,dLat=(b.lat-a.lat)*p,dLng=(b.lng-a.lng)*p;const x=Math.sin(dLat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dLng/2)**2;return Math.round(2*r*Math.asin(Math.sqrt(x)))}
export default function ReportForm(){
 const [reporter,setReporter]=useState<(Point&{accuracy:number})>();const [geoMessage,setGeoMessage]=useState("");const [lowAccuracy,setLowAccuracy]=useState(false);const [selected,setSelected]=useState<Point>();const [recenter,setRecenter]=useState(0);
 const [photo,setPhoto]=useState<File>();const [preview,setPreview]=useState("");const [error,setError]=useState("");const [submitting,setSubmitting]=useState(false);const [result,setResult]=useState<Result>();
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 const approximateDistance=useMemo(()=>reporter&&selected?distance(reporter,selected):undefined,[reporter,selected]);
 function locate(){if(!navigator.geolocation){setGeoMessage("ไม่สามารถตรวจสอบตำแหน่งผู้แจ้งได้ คุณยังสามารถแจ้งสถานการณ์ได้ แต่รายงานจะต้องรอการตรวจสอบ");return}setGeoMessage("กำลังค้นหาตำแหน่ง...");navigator.geolocation.getCurrentPosition(({coords})=>{setReporter({lat:coords.latitude,lng:coords.longitude,accuracy:coords.accuracy});setLowAccuracy(coords.accuracy>100);setGeoMessage("พบตำแหน่งปัจจุบันแล้ว");setRecenter(v=>v+1)},e=>{const m=e.code===e.PERMISSION_DENIED?"ไม่ได้รับอนุญาตให้ใช้ตำแหน่งปัจจุบัน":e.code===e.TIMEOUT?"หมดเวลาค้นหาตำแหน่งปัจจุบัน":"ไม่สามารถตรวจสอบตำแหน่งผู้แจ้งได้";setGeoMessage(`${m} คุณยังสามารถแจ้งสถานการณ์ได้ แต่รายงานจะต้องรอการตรวจสอบ`)},{enableHighAccuracy:true,timeout:10000,maximumAge:30000})}
 function choosePhoto(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];setError("");if(!file)return;if(!imageTypes.includes(file.type)){setError("รองรับเฉพาะรูปภาพ JPEG, PNG หรือ WebP");e.target.value="";return}if(file.size>MAX_PHOTO_BYTES){setError("รูปภาพมีขนาดใหญ่เกินไป");e.target.value="";return}if(preview)URL.revokeObjectURL(preview);setPhoto(file);setPreview(URL.createObjectURL(file))}
 function removePhoto(){if(preview)URL.revokeObjectURL(preview);setPhoto(undefined);setPreview("")}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(submitting)return;setError("");if(!selected){setError("กรุณาเลือกตำแหน่งน้ำท่วมบนแผนที่");return}const form=new FormData(e.currentTarget),water=Number(form.get("water_level_cm"));if(!Number.isFinite(water)||water<0){setError("กรุณาระบุระดับน้ำให้ถูกต้อง");return}const textValue=(name:string)=>{const value=form.get(name);return typeof value==="string"?value:""};setSubmitting(true);try{const payload:FloodReportPayload={flood_latitude:selected.lat,flood_longitude:selected.lng,water_level_cm:water,road_status:textValue("road_status"),vehicle_4w_status:textValue("vehicle_4w_status"),vehicle_6w_status:textValue("vehicle_6w_status"),vehicle_10w_status:textValue("vehicle_10w_status"),description:textValue("description")||null};if(reporter)Object.assign(payload,{reporter_latitude:reporter.lat,reporter_longitude:reporter.lng,reporter_gps_accuracy_m:reporter.accuracy});const created=await fetch(`${API_BASE_URL}/api/v1/flood-reports`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!created.ok)throw new Error();let data:Result=await created.json();if(photo){const upload=new FormData();upload.append("photo",photo);const uploaded=await fetch(`${API_BASE_URL}/api/v1/flood-reports/${encodeURIComponent(data.report_code)}/photos`,{method:"POST",body:upload});if(!uploaded.ok)throw new Error();data=await uploaded.json()}setResult(data)}catch{setError("ไม่สามารถส่งรายงานได้ กรุณาลองใหม่อีกครั้ง")}finally{setSubmitting(false)}}
 if(result){const copy=statusText[result.verification_status];return <main className="shell success"><div className="success-icon">✓</div><p className="eyebrow">ส่งรายงานสำเร็จ</p><h1>ขอบคุณสำหรับข้อมูล</h1><div className="report-code"><span>เลขที่รายงาน</span><strong>{result.report_code}</strong></div><section className="verification"><h2>{copy.title}</h2>{copy.detail&&<p>{copy.detail}</p>}</section><p className="muted">ระบบเก็บตำแหน่งปัจจุบันไว้เพื่อการตรวจสอบเท่านั้น และไม่แสดงเป็นตำแหน่งผู้แจ้งบนแผนที่สาธารณะ</p></main>}
 return <main className="shell"><header><p className="eyebrow">ช่วยกันดูแลชุมชน</p><h1>แจ้งสถานการณ์น้ำท่วม</h1><p>แจ้งจุดที่พบเห็นและสภาพการสัญจร ใช้เวลาเพียงไม่กี่นาที</p></header><form onSubmit={submit} noValidate>
  <section className="card map-card"><div className="step"><b>1</b><div><h2>ระบุตำแหน่งที่พบ</h2><p>แตะบนแผนที่เพื่อระบุตำแหน่งที่พบเห็นน้ำท่วม</p></div></div><FloodMap reporter={reporter} selected={selected} onPick={setSelected} recenterToken={recenter}/><div className="map-actions"><button type="button" className="secondary" onClick={locate}>◎ ใช้ตำแหน่งปัจจุบัน</button>{selected&&<span className="ok">✓ เลือกตำแหน่งน้ำท่วมแล้ว <button type="button" className="link" onClick={()=>setSelected(undefined)}>เปลี่ยนตำแหน่ง</button></span>}</div>{geoMessage&&<p role="status" className="notice">{geoMessage}{reporter&&` · ความแม่นยำประมาณ ${Math.round(reporter.accuracy)} เมตร`}</p>}{lowAccuracy&&<p className="warning">ตำแหน่งปัจจุบันอาจคลาดเคลื่อน โปรดเลือกจุดน้ำท่วมบนแผนที่อย่างระมัดระวัง</p>}{approximateDistance!==undefined&&<p className="distance">คุณอยู่ห่างจากจุดที่แจ้งประมาณ {approximateDistance.toLocaleString("th-TH")} เมตร</p>}</section>
  <section className="card"><div className="step"><b>2</b><div><h2>บอกสถานการณ์</h2><p>ข้อมูลคร่าว ๆ ช่วยให้ผู้อื่นวางแผนได้ดีขึ้น</p></div></div><label>ระดับน้ำโดยประมาณ <span className="required">*</span><div className="unit"><input name="water_level_cm" type="number" min="0" step="1" inputMode="decimal" required placeholder="30"/><span>ซม.</span></div></label><label>สภาพถนน<select name="road_status" defaultValue="UNKNOWN"><option value="UNKNOWN">ไม่ทราบ</option><option value="PASSABLE">ผ่านได้</option><option value="PARTIAL">ผ่านได้บางส่วน</option><option value="BLOCKED">ผ่านไม่ได้</option></select></label><fieldset><legend>รถประเภทใดสามารถผ่านได้</legend>{[["vehicle_4w_status","รถ 4 ล้อ"],["vehicle_6w_status","รถ 6 ล้อ"],["vehicle_10w_status","รถ 10 ล้อ"]].map(([name,label])=><label key={name}>{label}<select name={name} defaultValue="UNKNOWN"><option value="UNKNOWN">ไม่ทราบ</option><option value="PASSABLE">ผ่านได้</option><option value="BLOCKED">ผ่านไม่ได้</option></select></label>)}</fieldset><label>รายละเอียดเพิ่มเติม <span className="optional">(ไม่บังคับ)</span><textarea name="description" maxLength={2000} rows={4} placeholder="เช่น น้ำไหลแรง มีรถติดสะสม"/></label></section>
  <section className="card"><div className="step"><b>3</b><div><h2>รูปภาพประกอบ</h2><p>รูปภาพช่วยให้ตรวจสอบรายงานได้รวดเร็วขึ้น</p></div></div>{preview?<div className="preview"><Image src={preview} alt="ตัวอย่างรูปภาพน้ำท่วมที่เลือก" width={728} height={360} sizes="(min-width: 760px) 704px, calc(100vw - 72px)" unoptimized/><button type="button" className="remove" onClick={removePhoto}>ลบรูปภาพ</button></div>:<label className="upload">＋ เพิ่มรูปภาพ<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={choosePhoto}/><small>JPEG, PNG หรือ WebP ไม่เกิน 8 MB</small></label>}</section>
  <p className="privacy">🔒 ตำแหน่งปัจจุบันของคุณใช้เพื่อช่วยตรวจสอบความน่าเชื่อถือของรายงาน และจะไม่แสดงเป็นตำแหน่งผู้แจ้งบนแผนที่สาธารณะ</p>{error&&<div className="form-error" role="alert">{error}</div>}<button className="primary submit" disabled={submitting}>{submitting?"กำลังส่งรายงาน...":"ส่งรายงานน้ำท่วม"}</button>
 </form></main>
}
