import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";import {afterEach,beforeEach,describe,expect,it,vi} from "vitest";import ReportForm from "./report-form";
vi.mock("next/dynamic",()=>({default:()=>({onPick}:{onPick:(p:{lat:number;lng:number})=>void})=><button type="button" onClick={()=>onPick({lat:14.1,lng:100.5})}>เลือกจุดทดสอบ</button>}));
const ok=(body:object)=>Promise.resolve({ok:true,json:()=>Promise.resolve(body)} as Response);
beforeEach(()=>{vi.restoreAllMocks();Object.defineProperty(global.URL,"createObjectURL",{value:vi.fn(()=>"blob:preview"),configurable:true});Object.defineProperty(global.URL,"revokeObjectURL",{value:vi.fn(),configurable:true})});
afterEach(cleanup);
describe("public flood form",()=>{
 it("renders without login or manual coordinate fields",()=>{render(<ReportForm/>);expect(screen.getByRole("heading",{name:"แจ้งสถานการณ์น้ำท่วม"})).toBeInTheDocument();expect(screen.queryByLabelText(/latitude|longitude/i)).not.toBeInTheDocument()});
 it("captures GPS accuracy and handles denial",()=>{const getCurrentPosition=vi.fn((success:(position:{coords:{latitude:number;longitude:number;accuracy:number}})=>void)=>success({coords:{latitude:14,longitude:100,accuracy:18}}));Object.defineProperty(navigator,"geolocation",{value:{getCurrentPosition},configurable:true});render(<ReportForm/>);fireEvent.click(screen.getByText(/ใช้ตำแหน่งปัจจุบัน/));expect(screen.getByText(/ความแม่นยำประมาณ 18 เมตร/)).toBeInTheDocument()});
 it("shows permission denial without blocking",()=>{Object.defineProperty(navigator,"geolocation",{value:{getCurrentPosition:(_:unknown,fail:(x:object)=>void)=>fail({code:1,PERMISSION_DENIED:1})},configurable:true});render(<ReportForm/>);fireEvent.click(screen.getByText(/ใช้ตำแหน่งปัจจุบัน/));expect(screen.getByText(/ไม่ได้รับอนุญาต/)).toBeInTheDocument()});
 it("requires map selection and validates water",()=>{render(<ReportForm/>);const form=screen.getByRole("button",{name:"ส่งรายงานน้ำท่วม"}).closest("form")!;fireEvent.submit(form);expect(screen.getByRole("alert")).toHaveTextContent("กรุณาเลือกตำแหน่ง");fireEvent.click(screen.getByText("เลือกจุดทดสอบ"));fireEvent.submit(form);expect(screen.getByRole("alert")).toHaveTextContent("กรุณาระบุระดับน้ำ")});
 it("previews and removes a supported photo, rejects unsupported and oversized",()=>{render(<ReportForm/>);const input=document.querySelector('input[type="file"]')!;fireEvent.change(input,{target:{files:[new File(["x"],"f.jpg",{type:"image/jpeg"})]}});expect(screen.getByAltText(/ตัวอย่าง/)).toBeInTheDocument();fireEvent.click(screen.getByText("ลบรูปภาพ"));expect(screen.queryByAltText(/ตัวอย่าง/)).not.toBeInTheDocument();fireEvent.change(document.querySelector('input[type="file"]')!,{target:{files:[new File(["x"],"f.gif",{type:"image/gif"})]}});expect(screen.getByRole("alert")).toHaveTextContent("รองรับเฉพาะ")});
 it("sends the user-entered decimal water level, maps statuses, and prevents double submit",async()=>{const fetchMock=vi.fn(()=>ok({report_code:"FR-20260924-00001",verification_status:"VERIFIED"}));vi.stubGlobal("fetch",fetchMock);render(<ReportForm/>);fireEvent.click(screen.getByText("เลือกจุดทดสอบ"));fireEvent.change(screen.getByLabelText(/ระดับน้ำ/),{target:{value:"30.5"}});fireEvent.change(screen.getByLabelText("สภาพถนน"),{target:{value:"PARTIAL"}});fireEvent.click(screen.getByText("ส่งรายงานน้ำท่วม"));fireEvent.click(screen.getByText("กำลังส่งรายงาน..."));await screen.findByText("ขอบคุณสำหรับข้อมูล");expect(screen.getByText("ตรวจสอบตำแหน่งแล้ว")).toBeInTheDocument();expect(fetchMock).toHaveBeenCalledTimes(1);const body=JSON.parse(((fetchMock.mock.calls[0] as unknown) as [string,RequestInit])[1].body as string);expect(body.water_level_cm).toBe(30.5);expect(body.road_status).toBe("PARTIAL");expect(body.vehicle_4w_status).toBe("UNKNOWN")});
 it.each([["PENDING_REVIEW","รอตรวจสอบ"],["UNVERIFIED","ยังไม่ได้ตรวจสอบ"]])("maps %s response",async(status,message)=>{vi.stubGlobal("fetch",vi.fn(()=>ok({report_code:"FR-1",verification_status:status})));render(<ReportForm/>);fireEvent.click(screen.getByText("เลือกจุดทดสอบ"));fireEvent.change(screen.getByLabelText(/ระดับน้ำ/),{target:{value:"0"}});fireEvent.click(screen.getByText("ส่งรายงานน้ำท่วม"));await waitFor(()=>expect(screen.getByText(message)).toBeInTheDocument())});
});
