"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { API_BASE_URL } from "@/lib/config";
import { BmaObservation,Branch,BranchSituation,DC,loadAllBranchSituations,matchesSearch,Period,PublicReport,RouteImpact,RouteResult,SITUATIONS,Situation,Summary,routeSituationLabels,situationColors,situationLabels } from "@/lib/operations";
const OperationsMap=dynamic(()=>import("@/components/OperationsMap"),{ssr:false,loading:()=> <div className="operations-map map-loading">กำลังเปิดแผนที่…</div>});
const emptySummary:Summary={gistda_direct:0,multi_source_nearby:0,gistda_nearby:0,public_nearby:0,no_nearby_flood:0,source_data_incomplete:0};
const api=async<T,>(path:string,init?:RequestInit):Promise<T>=>{const r=await fetch(`${API_BASE_URL}${path}`,init);if(!r.ok)throw new Error(String(r.status));return r.json()};
const params=(period:Period,lookback:number,offset=0)=>`period=${period}&gistda_proximity_km=5&public_proximity_km=5&public_lookback_hours=${lookback}&limit=1000&offset=${offset}`;

export default function OperationsDashboard(){
 const [period,setPeriod]=useState<Period>("3DAYS"),[lookback,setLookback]=useState(24),[branches,setBranches]=useState<Branch[]>([]),[situations,setSituations]=useState<BranchSituation[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[dcs,setDcs]=useState<DC[]>([]),[reports,setReports]=useState<PublicReport[]>([]),[gistda,setGistda]=useState<GeoJSON.FeatureCollection|null>(null),[selected,setSelected]=useState<string>(),[query,setQuery]=useState(""),[filter,setFilter]=useState<Situation|"ALL">("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState<Date>();
 const [bma,setBma]=useState<BmaObservation[]>([]);
 const [layers,setLayers]=useState({branches:true,dcs:true,gistda:true,bma:true,reports:true,route:true}),[dcCode,setDcCode]=useState(""),[vehicle,setVehicle]=useState("4W"),[route,setRoute]=useState<RouteResult|null>(null),[impact,setImpact]=useState<RouteImpact|null>(null),[routeBusy,setRouteBusy]=useState(false),[routeError,setRouteError]=useState("");
 const loadController=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{loadController.current?.abort();const controller=new AbortController();loadController.current=controller;setLoading(true);setError("");try{const situationPage=await loadAllBranchSituations(offset=>api<{summary:Summary;items:BranchSituation[]}>(`/api/v1/branch-flood-situation?${params(period,lookback,offset)}`,{signal:controller.signal}));const since=new Date(Date.now()-lookback*3600000).toISOString();const [b,dc,g,r,bmaRows]=await Promise.all([api<Branch[]>("/api/v1/branches",{signal:controller.signal}),api<DC[]>("/api/v1/distribution-centers",{signal:controller.signal}),api<GeoJSON.FeatureCollection>(`/api/v1/gistda/flood?period=${period.toLowerCase()}`,{signal:controller.signal}),api<PublicReport[]>(`/api/v1/flood-reports?status=ACTIVE&reported_from=${encodeURIComponent(since)}`,{signal:controller.signal}),api<BmaObservation[]>("/api/v1/bma/road-water?active=true&limit=1000",{signal:controller.signal})]);if(controller.signal.aborted)return;setSummary(situationPage.summary);setSituations(situationPage.items);setBranches(b);setDcs(dc.filter(x=>x.status==="ACTIVE"&&x.dc_code!=="TEST-DC-01"));setGistda(g);setReports(r);setBma(bmaRows);setUpdated(new Date())}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setError("ไม่สามารถโหลดข้อมูลปฏิบัติการได้ กรุณาตรวจสอบ API แล้วลองใหม่")}finally{if(loadController.current===controller){setLoading(false);loadController.current=null}}},[period,lookback]);
 useEffect(()=>{void refresh();return()=>loadController.current?.abort()},[refresh]);
 const branchMap=useMemo(()=>new Map(branches.map(b=>[b.store_number,b])),[branches]);const chosen=situations.find(x=>x.store_number===selected);const visible=useMemo(()=>situations.filter(x=>filter==="ALL"||x.situation===filter),[situations,filter]);
 const results=useMemo(()=>query.trim()?[...branches.filter(b=>matchesSearch(query,b)).slice(0,8).map(b=>({key:b.store_number,label:`${b.store_number} · ${b.store_name} · ${b.city}`,kind:"branch"})),...dcs.filter(d=>matchesSearch(query,d)).slice(0,4).map(d=>({key:d.dc_code,label:`DC ${d.dc_code} · ${d.dc_name}`,kind:"dc"}))]:[],[query,branches,dcs]);
 const calculate=async()=>{if(!dcCode||!selected)return;setRouteBusy(true);setRouteError("");setRoute(null);setImpact(null);try{const value=await api<RouteResult>("/api/v1/routes/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin:{type:"DC",code:dcCode},destination:{type:"BRANCH",code:selected},vehicle_profile:vehicle})});setRoute(value);setImpact(await api<RouteImpact>(`/api/v1/routes/${value.route_id}/flood-impact`))}catch{setRouteError("คำนวณเส้นทางไม่ได้ โปรดตรวจสอบ Valhalla และลองอีกครั้ง")}finally{setRouteBusy(false)}};
 const cards:Array<[string,number,Situation?]>=[["สาขาทั้งหมด",Object.values(summary).reduce((a,b)=>a+b,0)],[situationLabels.GISTDA_DIRECT,summary.gistda_direct,"GISTDA_DIRECT"],[situationLabels.MULTI_SOURCE_NEARBY,summary.multi_source_nearby,"MULTI_SOURCE_NEARBY"],[situationLabels.GISTDA_NEARBY,summary.gistda_nearby,"GISTDA_NEARBY"],[situationLabels.PUBLIC_NEARBY,summary.public_nearby,"PUBLIC_NEARBY"],[situationLabels.NO_NEARBY_FLOOD,summary.no_nearby_flood,"NO_NEARBY_FLOOD"],[situationLabels.SOURCE_DATA_INCOMPLETE,summary.source_data_incomplete,"SOURCE_DATA_INCOMPLETE"]];
 return <main className="operations"><header className="ops-header"><div className="ops-brand"><strong>FLOOD INTELLIGENCE</strong><nav><span className="active">แผนที่</span><span>เส้นทาง</span><Link href="/report-flood">รายงาน</Link></nav></div><div className="header-actions"><span>อัปเดต {updated?updated.toLocaleString("th-TH"):"—"}</span><button className="secondary" onClick={()=>void refresh()} disabled={loading}>↻ ล่าสุด</button><Link className="primary" href="/report-flood">+ รายงานน้ำท่วม</Link></div></header>
 <div className="ops-grid"><aside className="ops-panel"><div className="panel-heading"><span>ชั้นข้อมูล</span><small>{period} · {lookback} ชม.</small></div>{error&&<div className="form-error" role="alert">{error}</div>}<fieldset className="layer-list">{Object.entries({branches:`สาขา · ${visible.length.toLocaleString()}`,dcs:`DC · ${dcs.length}`,gistda:`GISTDA · ${gistda?.features.length??0}`,bma:`BMA · ${bma.length}`,reports:`Public · ${reports.length}`,route:route?"Route · 1":"Route"}).map(([k,v])=><label className="check" key={k}><input type="checkbox" checked={layers[k as keyof typeof layers]} onChange={()=>setLayers(x=>({...x,[k]:!x[k as keyof typeof x]}))}/><span>{v}</span></label>)}</fieldset><div className="hdms-layer-note"><span>HDMS*</span><small>แสดงใน Route Evidence</small></div><section className="layer-search"><h2>ค้นหา</h2><input aria-label="ค้นหาสาขาหรือศูนย์กระจายสินค้า" placeholder="สาขา ชื่อ เมือง หรือ DC" value={query} onChange={e=>setQuery(e.target.value)}/>{results.length>0&&<div className="search-results">{results.map(r=><button key={`${r.kind}-${r.key}`} onClick={()=>{if(r.kind==="branch")setSelected(r.key);else setDcCode(r.key);setQuery("")}}>{r.label}</button>)}</div>}</section><details className="advanced-filter"><summary>ตัวกรองเพิ่มเติม</summary><label>ช่วง GISTDA<select value={period} onChange={e=>setPeriod(e.target.value as Period)}>{["1DAY","3DAYS","7DAYS","30DAYS"].map(x=><option key={x}>{x}</option>)}</select></label><label>สถานการณ์<select value={filter} onChange={e=>setFilter(e.target.value as Situation|"ALL")}><option value="ALL">ทั้งหมด</option>{SITUATIONS.map(x=><option value={x} key={x}>{situationLabels[x]}</option>)}</select></label><label>Public ย้อนหลัง<select value={lookback} onChange={e=>setLookback(Number(e.target.value))}><option value={6}>6 ชั่วโมง</option><option value={24}>24 ชั่วโมง</option><option value={72}>72 ชั่วโมง</option><option value={168}>7 วัน</option></select></label></details></aside>
 <section className="map-area"><OperationsMap branches={visible} dcs={dcs} gistda={gistda} bma={bma} reports={reports} route={route} impact={impact} layers={layers} selected={chosen?{lat:chosen.latitude,lng:chosen.longitude,key:chosen.store_number}:undefined} onSelect={setSelected}/>{dcs.length===0&&<div className="map-notice">ยังไม่มี DC จริงในระบบ (ซ่อน TEST-DC-01)</div>}</section>
 <aside className={`detail-panel ${chosen?"open":""}`}><div className="panel-heading"><span>รายละเอียด</span>{chosen&&<button className="panel-close" aria-label="ปิดรายละเอียด" onClick={()=>setSelected(undefined)}>×</button>}</div>{chosen?<><span className="eyebrow">สาขา {chosen.store_number}</span><h2>{chosen.store_name}</h2><p>{chosen.city} · รถ {branchMap.get(chosen.store_number)?.vehicle_type||"ไม่มีข้อมูล"}</p><div className="situation" style={{borderColor:situationColors[chosen.situation]}}><strong>{situationLabels[chosen.situation]}</strong><code>{chosen.situation}</code></div><h3 className="evidence-title">Evidence</h3><Evidence title="GISTDA" available={chosen.gistda.data_available} lines={[chosen.gistda.inside_flood_polygon?"อยู่ภายใน polygon":"ไม่อยู่ภายใน polygon",chosen.gistda.nearest_flood_distance_km==null?"ไม่มีระยะที่เกี่ยวข้อง":`ระยะใกล้สุด ${chosen.gistda.nearest_flood_distance_km.toFixed(2)} กม.`]}/><Evidence title="Public" available={chosen.public.data_available} lines={[chosen.public.nearest_report_code?`รายงาน ${chosen.public.nearest_report_code}`:"ไม่พบรายงานใกล้เคียง",chosen.public.nearest_report_distance_km==null?"ไม่มีระยะที่เกี่ยวข้อง":`ระยะใกล้สุด ${chosen.public.nearest_report_distance_km.toFixed(2)} กม.`]}/><div className="route-planner"><div className="route-heading"><h3>Route</h3><div className="vehicle-chips">{["4W","6W","10W"].map(x=><button key={x} className={vehicle===x?"active":""} onClick={()=>setVehicle(x)}>{x}</button>)}</div></div>{dcs.length?<><select aria-label="ต้นทาง DC" value={dcCode} onChange={e=>setDcCode(e.target.value)}><option value="">เลือก DC ต้นทาง</option>{dcs.map(d=><option value={d.dc_code} key={d.dc_code}>{d.dc_code} · {d.dc_name}</option>)}</select><button className="primary route-button" disabled={!dcCode||routeBusy} onClick={()=>void calculate()}>{routeBusy?"กำลังคำนวณ…":"คำนวณเส้นทาง"}</button></>:<p className="warning">ยังไม่มี DC สำหรับวางแผนเส้นทาง</p>}{routeError&&<div className="form-error" role="alert">{routeError}</div>}{route&&<RouteCard route={route} impact={impact}/>}</div></>:<div className="empty-detail"><strong>Branch / Route</strong><p>เลือกสาขาบนแผนที่หรือค้นหาจากแถบด้านซ้าย เพื่อดู Evidence และวางแผนเส้นทาง</p><div className="evidence-placeholder"><span>GISTDA</span><span>HDMS</span><span>BMA</span><span>Public</span></div><div className="vehicle-chips preview">{["4W","6W","10W"].map(x=><span key={x}>{x}</span>)}</div></div>}</aside></div>
 <footer className="source-status"><span className="source-live">● GISTDA</span><span className="source-live">● HDMS</span><span className="source-live">● BMA</span><span className="source-live">● Public</span><span className="status-updated">Updated {updated?updated.toLocaleString("th-TH"):"—"}</span></footer></main>
}
function Evidence({title,available,lines}:{title:string;available:boolean;lines:string[]}){return <div className="evidence"><h3>{title}</h3><span className={available?"source-ok":"source-missing"}>{available?"มีข้อมูลแหล่งที่มา":"ข้อมูลแหล่งที่มาไม่พร้อม"}</span>{lines.filter(Boolean).map(x=><p key={x}>{x}</p>)}</div>}
function RouteCard({route,impact}:{route:RouteResult;impact:RouteImpact|null}){return <div className="route-card"><h3>ผลเส้นทางถนน</h3><dl><dt>ระยะทาง</dt><dd>{route.distance_km.toFixed(1)} กม.</dd><dt>เวลาโดยประมาณ</dt><dd>{route.duration_minutes.toFixed(0)} นาที</dd><dt>รถ / ผู้ให้บริการ</dt><dd>{route.vehicle_profile} · {route.routing_provider}</dd><dt>คำนวณเมื่อ</dt><dd>{new Date(route.calculated_at).toLocaleString("th-TH")}</dd></dl>{impact?<><h3>ผลกระทบน้ำท่วมต่อเส้นทาง</h3><div className="situation"><strong>{routeSituationLabels[impact.flood_situation]||impact.flood_situation}</strong><code>{impact.flood_situation}</code></div><p>GISTDA: {impact.gistda_evidence.length} · HDMS: {impact.hdms_evidence.length} · BMA: {impact.bma_evidence.length} · Public: {impact.public_report_evidence.length}</p>{impact.official_road_closure&&<p className="official-closure"><strong>HDMS: พบถนนที่ทางการระบุว่าผ่านไม่ได้บนเส้นทาง</strong></p>}{impact.hdms_evidence.map(e=><p key={`hdms-${e.incident_id}`}>HDMS {e.section_name||e.road_code||e.case_id||e.incident_id}: {e.road_status}{e.water_depth_cm!=null?` · น้ำ ${e.water_depth_cm} ซม.`:""}</p>)}{impact.bma_evidence.map(e=><p key={`bma-${e.observation_id}`}>BMA {e.station_name||e.road_name||e.observation_id}{e.water_level_cm!=null?` · น้ำ ${e.water_level_cm} ซม.`:""} · ห่างเส้นทาง {e.distance_to_route_meters.toFixed(0)} ม.</p>)}<p>{impact.source_data_status.complete?"ข้อมูลแหล่งที่มาครบ":"ข้อมูลแหล่งที่มายังไม่ครบ"} · ประเมิน {new Date(impact.evaluated_at).toLocaleString("th-TH")}</p></>:<p>กำลังตรวจสอบหลักฐานน้ำท่วม…</p>}</div>}
