"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { API_BASE_URL } from "@/lib/config";
import { Branch,BranchSituation,DC,matchesSearch,Period,PublicReport,RouteImpact,RouteResult,SITUATIONS,Situation,Summary,routeSituationLabels,situationColors,situationLabels } from "@/lib/operations";
const OperationsMap=dynamic(()=>import("@/components/OperationsMap"),{ssr:false,loading:()=> <div className="operations-map map-loading">กำลังเปิดแผนที่…</div>});
const emptySummary:Summary={gistda_direct:0,multi_source_nearby:0,gistda_nearby:0,public_nearby:0,no_nearby_flood:0,source_data_incomplete:0};
const api=async<T,>(path:string,init?:RequestInit):Promise<T>=>{const r=await fetch(`${API_BASE_URL}${path}`,init);if(!r.ok)throw new Error(String(r.status));return r.json()};
const params=(period:Period,lookback:number,offset=0)=>`period=${period}&gistda_proximity_km=5&public_proximity_km=5&public_lookback_hours=${lookback}&limit=1000&offset=${offset}`;

export default function OperationsDashboard(){
 const [period,setPeriod]=useState<Period>("3DAYS"),[lookback,setLookback]=useState(24),[branches,setBranches]=useState<Branch[]>([]),[situations,setSituations]=useState<BranchSituation[]>([]),[summary,setSummary]=useState<Summary>(emptySummary),[dcs,setDcs]=useState<DC[]>([]),[reports,setReports]=useState<PublicReport[]>([]),[gistda,setGistda]=useState<GeoJSON.FeatureCollection|null>(null),[selected,setSelected]=useState<string>(),[query,setQuery]=useState(""),[filter,setFilter]=useState<Situation|"ALL">("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState<Date>();
 const [layers,setLayers]=useState({branches:true,dcs:true,gistda:true,reports:true,route:true}),[dcCode,setDcCode]=useState(""),[vehicle,setVehicle]=useState("4W"),[route,setRoute]=useState<RouteResult|null>(null),[impact,setImpact]=useState<RouteImpact|null>(null),[routeBusy,setRouteBusy]=useState(false),[routeError,setRouteError]=useState("");
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const first=await api<{summary:Summary;items:BranchSituation[]}>(`/api/v1/branch-flood-situation?${params(period,lookback)}`);const all=[...first.items];let offset=1000;while(all.length===offset){const p=await api<{items:BranchSituation[]}>(`/api/v1/branch-flood-situation?${params(period,lookback,offset)}`);all.push(...p.items);if(p.items.length<1000)break;offset+=1000}const since=new Date(Date.now()-lookback*3600000).toISOString();const [b,dc,g,r]=await Promise.all([api<Branch[]>("/api/v1/branches"),api<DC[]>("/api/v1/distribution-centers"),api<GeoJSON.FeatureCollection>(`/api/v1/gistda/flood?period=${period.toLowerCase()}`),api<PublicReport[]>(`/api/v1/flood-reports?status=ACTIVE&reported_from=${encodeURIComponent(since)}`)]);setSummary(first.summary);setSituations(all);setBranches(b);setDcs(dc.filter(x=>x.status==="ACTIVE"&&x.dc_code!=="TEST-DC-01"));setGistda(g);setReports(r);setUpdated(new Date())}catch{setError("ไม่สามารถโหลดข้อมูลปฏิบัติการได้ กรุณาตรวจสอบ API แล้วลองใหม่")}finally{setLoading(false)}},[period,lookback]);
 useEffect(()=>{void refresh()},[refresh]);
 const branchMap=useMemo(()=>new Map(branches.map(b=>[b.store_number,b])),[branches]);const chosen=situations.find(x=>x.store_number===selected);const visible=useMemo(()=>situations.filter(x=>filter==="ALL"||x.situation===filter),[situations,filter]);
 const results=useMemo(()=>query.trim()?[...branches.filter(b=>matchesSearch(query,b)).slice(0,8).map(b=>({key:b.store_number,label:`${b.store_number} · ${b.store_name} · ${b.city}`,kind:"branch"})),...dcs.filter(d=>matchesSearch(query,d)).slice(0,4).map(d=>({key:d.dc_code,label:`DC ${d.dc_code} · ${d.dc_name}`,kind:"dc"}))]:[],[query,branches,dcs]);
 const calculate=async()=>{if(!dcCode||!selected)return;setRouteBusy(true);setRouteError("");setRoute(null);setImpact(null);try{const value=await api<RouteResult>("/api/v1/routes/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({origin:{type:"DC",code:dcCode},destination:{type:"BRANCH",code:selected},vehicle_profile:vehicle})});setRoute(value);setImpact(await api<RouteImpact>(`/api/v1/routes/${value.route_id}/flood-impact`))}catch{setRouteError("คำนวณเส้นทางไม่ได้ โปรดตรวจสอบ Valhalla และลองอีกครั้ง")}finally{setRouteBusy(false)}};
 const cards:Array<[string,number,Situation?]>=[["สาขาทั้งหมด",Object.values(summary).reduce((a,b)=>a+b,0)],[situationLabels.GISTDA_DIRECT,summary.gistda_direct,"GISTDA_DIRECT"],[situationLabels.MULTI_SOURCE_NEARBY,summary.multi_source_nearby,"MULTI_SOURCE_NEARBY"],[situationLabels.GISTDA_NEARBY,summary.gistda_nearby,"GISTDA_NEARBY"],[situationLabels.PUBLIC_NEARBY,summary.public_nearby,"PUBLIC_NEARBY"],[situationLabels.NO_NEARBY_FLOOD,summary.no_nearby_flood,"NO_NEARBY_FLOOD"],[situationLabels.SOURCE_DATA_INCOMPLETE,summary.source_data_incomplete,"SOURCE_DATA_INCOMPLETE"]];
 return <main className="operations"><header className="ops-header"><div><span className="eyebrow">TRANSPORT CONTROL TOWER</span><h1>Flood Intelligence</h1><p>ภาพรวมหลักฐานสถานการณ์น้ำท่วมสำหรับการปฏิบัติการ</p></div><div className="header-actions"><span>อัปเดต {updated?updated.toLocaleString("th-TH"):"—"}</span><button className="secondary" onClick={()=>void refresh()} disabled={loading}>↻ รีเฟรช</button><Link className="primary" href="/report-flood">+ รายงานน้ำท่วม</Link></div></header>
 <div className="ops-grid"><aside className="ops-panel"><section><div className="section-title"><h2>สรุปสถานการณ์</h2><span>{period} · {lookback} ชม.</span></div>{error&&<div className="form-error" role="alert">{error}</div>}<div className="kpis">{cards.map(([label,value,s])=><button key={label} className="kpi" onClick={()=>s&&setFilter(s)}><span className="dot" style={{background:s?situationColors[s]:"#073b5c"}}/><strong>{loading?"—":value.toLocaleString()}</strong><small>{label}</small></button>)}</div></section>
 <section><h2>ค้นหาสาขา / DC</h2><input aria-label="ค้นหาสาขาหรือศูนย์กระจายสินค้า" placeholder="เลขสาขา ชื่อ เมือง หรือรหัส DC" value={query} onChange={e=>setQuery(e.target.value)}/>{results.length>0&&<div className="search-results">{results.map(r=><button key={`${r.kind}-${r.key}`} onClick={()=>{if(r.kind==="branch")setSelected(r.key);else setDcCode(r.key);setQuery("")}}>{r.label}</button>)}</div>}</section>
 <section className="filters"><h2>ตัวกรอง</h2><label>ช่วงข้อมูล GISTDA<select value={period} onChange={e=>setPeriod(e.target.value as Period)}>{["1DAY","3DAYS","7DAYS","30DAYS"].map(x=><option key={x}>{x}</option>)}</select></label><label>สถานการณ์สาขา<select value={filter} onChange={e=>setFilter(e.target.value as Situation|"ALL")}><option value="ALL">ทั้งหมด</option>{SITUATIONS.map(x=><option value={x} key={x}>{situationLabels[x]}</option>)}</select></label><label>รายงานย้อนหลัง<select value={lookback} onChange={e=>setLookback(Number(e.target.value))}><option value={6}>6 ชั่วโมง</option><option value={24}>24 ชั่วโมง</option><option value={72}>72 ชั่วโมง</option><option value={168}>7 วัน</option></select></label><fieldset><legend>ชั้นข้อมูล</legend>{Object.entries({branches:"สาขา",dcs:"ศูนย์กระจายสินค้า",gistda:"พื้นที่น้ำท่วม GISTDA",reports:"รายงานสาธารณะ",route:"เส้นทางที่เลือก"}).map(([k,v])=><label className="check" key={k}><input type="checkbox" checked={layers[k as keyof typeof layers]} onChange={()=>setLayers(x=>({...x,[k]:!x[k as keyof typeof x]}))}/>{v}</label>)}</fieldset></section></aside>
 <section className="map-area"><OperationsMap branches={visible} dcs={dcs} gistda={gistda} reports={reports} route={route} impact={impact} layers={layers} selected={chosen?{lat:chosen.latitude,lng:chosen.longitude,key:chosen.store_number}:undefined} onSelect={setSelected}/><div className="map-status">แสดง {visible.length.toLocaleString()} สาขา · {gistda?.features.length??0} พื้นที่ GISTDA · {reports.length} รายงาน</div>{dcs.length===0&&<div className="map-notice">ยังไม่มีศูนย์กระจายสินค้าจริงในระบบ (ซ่อนข้อมูล TEST-DC-01)</div>}</section>
 <aside className={`detail-panel ${chosen?"open":""}`}><button className="panel-close" aria-label="ปิดรายละเอียด" onClick={()=>setSelected(undefined)}>×</button>{chosen?<><span className="eyebrow">สาขา {chosen.store_number}</span><h2>{chosen.store_name}</h2><p>{chosen.city} · รถ {branchMap.get(chosen.store_number)?.vehicle_type||"ไม่มีข้อมูล"}</p><div className="situation" style={{borderColor:situationColors[chosen.situation]}}><strong>{situationLabels[chosen.situation]}</strong><code>{chosen.situation}</code></div><Evidence title="หลักฐาน GISTDA" available={chosen.gistda.data_available} lines={[chosen.gistda.inside_flood_polygon?"อยู่ภายใน polygon":"ไม่อยู่ภายใน polygon",chosen.gistda.nearest_flood_distance_km==null?"ไม่มีระยะที่เกี่ยวข้อง":`ระยะใกล้สุด ${chosen.gistda.nearest_flood_distance_km.toFixed(2)} กม.`,`ช่วงข้อมูล ${chosen.gistda.period}`]}/><Evidence title="รายงานสาธารณะ" available={chosen.public.data_available} lines={[chosen.public.nearest_report_code?`รายงาน ${chosen.public.nearest_report_code}`:"ไม่พบรายงานใกล้เคียง",chosen.public.nearest_report_distance_km==null?"ไม่มีระยะที่เกี่ยวข้อง":`ระยะใกล้สุด ${chosen.public.nearest_report_distance_km.toFixed(2)} กม.`,chosen.public.nearest_report_verification_status?`การตรวจสอบ: ${chosen.public.nearest_report_verification_status}`:"",chosen.public.nearest_report_reported_at?`รายงานเมื่อ ${new Date(chosen.public.nearest_report_reported_at).toLocaleString("th-TH")}`:""]}/><hr/><h2>วางแผนเส้นทางจาก DC</h2>{dcs.length?<><label>ต้นทาง<select value={dcCode} onChange={e=>setDcCode(e.target.value)}><option value="">เลือก DC</option>{dcs.map(d=><option value={d.dc_code} key={d.dc_code}>{d.dc_code} · {d.dc_name}</option>)}</select></label><label>ประเภทรถ<select value={vehicle} onChange={e=>setVehicle(e.target.value)}>{["4W","6W","10W"].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary route-button" disabled={!dcCode||routeBusy} onClick={()=>void calculate()}>{routeBusy?"กำลังคำนวณ…":"คำนวณเส้นทาง"}</button></>:<p className="warning">ยังไม่มี DC สำหรับวางแผนเส้นทาง</p>}{routeError&&<div className="form-error" role="alert">{routeError}</div>}{route&&<RouteCard route={route} impact={impact}/>}</>:<div className="empty-detail"><strong>เลือกสาขาบนแผนที่</strong><p>หรือค้นหาด้วยเลขสาขา ชื่อ และเมือง เพื่อดูหลักฐานและวางแผนเส้นทาง</p></div>}</aside></div></main>
}
function Evidence({title,available,lines}:{title:string;available:boolean;lines:string[]}){return <div className="evidence"><h3>{title}</h3><span className={available?"source-ok":"source-missing"}>{available?"มีข้อมูลแหล่งที่มา":"ข้อมูลแหล่งที่มาไม่พร้อม"}</span>{lines.filter(Boolean).map(x=><p key={x}>{x}</p>)}</div>}
function RouteCard({route,impact}:{route:RouteResult;impact:RouteImpact|null}){return <div className="route-card"><h3>ผลเส้นทางถนน</h3><dl><dt>ระยะทาง</dt><dd>{route.distance_km.toFixed(1)} กม.</dd><dt>เวลาโดยประมาณ</dt><dd>{route.duration_minutes.toFixed(0)} นาที</dd><dt>รถ / ผู้ให้บริการ</dt><dd>{route.vehicle_profile} · {route.routing_provider}</dd><dt>คำนวณเมื่อ</dt><dd>{new Date(route.calculated_at).toLocaleString("th-TH")}</dd></dl>{impact?<><h3>ผลกระทบน้ำท่วมต่อเส้นทาง</h3><div className="situation"><strong>{routeSituationLabels[impact.flood_situation]||impact.flood_situation}</strong><code>{impact.flood_situation}</code></div><p>GISTDA: {impact.gistda_evidence.length} หลักฐาน · รายงานสาธารณะ: {impact.public_report_evidence.length} รายการ</p><p>{impact.source_data_status.complete?"ข้อมูลแหล่งที่มาครบ":"ข้อมูลแหล่งที่มายังไม่ครบ"} · ประเมิน {new Date(impact.evaluated_at).toLocaleString("th-TH")}</p></>:<p>กำลังตรวจสอบหลักฐานน้ำท่วม…</p>}</div>}
