import {cleanup,fireEvent,render,screen} from "@testing-library/react";
import {afterEach,describe,expect,it,vi} from "vitest";
vi.mock("next/dynamic",()=>({default:()=>()=> <div aria-label="แผนที่ปฏิบัติการ"/>}));
vi.stubGlobal("fetch",vi.fn().mockRejectedValue(new Error("offline")));
import OperationsDashboard,{RouteCard} from "./operations-dashboard";
afterEach(cleanup);
describe("OperationsDashboard",()=>{
 it("renders controls and friendly API error",async()=>{render(<OperationsDashboard/>);expect(screen.getByText("สถานการณ์ปัจจุบัน")).toBeInTheDocument();expect(screen.getByText("ตัวกรองขั้นสูง")).toBeInTheDocument();expect(screen.getByLabelText("ค้นหาสาขาหรือศูนย์กระจายสินค้า")).toBeInTheDocument();expect(await screen.findByRole("alert")).toHaveTextContent("ไม่สามารถโหลดข้อมูลปฏิบัติการได้")});
 it("loads the actual HDMS count and enables its layer toggle by default",async()=>{
  vi.mocked(fetch).mockImplementation(async input=>{const url=String(input);let body:unknown=[];if(url.includes("branch-flood-situation"))body={summary:{gistda_direct:0,multi_source_nearby:0,gistda_nearby:0,public_nearby:0,no_nearby_flood:0,source_data_incomplete:0},items:[]};else if(url.includes("gistda/flood"))body={type:"FeatureCollection",features:[]};else if(url.includes("hdms/incidents"))body=[{id:1},{id:2}];return new Response(JSON.stringify(body),{status:200,headers:{"Content-Type":"application/json"}})});
  render(<OperationsDashboard/>);const toggle=await screen.findByLabelText("HDMS");expect(toggle).toBeChecked();expect(toggle.closest("label")).toHaveTextContent("HDMS2");expect(toggle.closest("label")?.querySelector(".layer-swatch")).toHaveStyle({backgroundColor:"#d43227"});expect(screen.getByLabelText("สาขา").closest("label")?.querySelector(".layer-swatch")).toHaveStyle({backgroundColor:"#27826b"});fireEvent.click(toggle);expect(toggle).not.toBeChecked();
 });
 it("shows blocked operational warning, hazard details, and disables navigation",()=>{const route={route_id:null,origin_type:"DC" as const,origin_code:"WNDC",destination_code:"5537",vehicle_profile:"4W",distance_km:160.001,duration_minutes:123.2,route_geometry:{type:"LineString" as const,coordinates:[]},routing_provider:"VALHALLA",calculated_at:"2026-10-05",safety_state:"BLOCKED" as const,avoidance_attempted:true,blocking_hazards:[{source:"HDMS",case_id:"202609280016",section_name:"ทางหลวง 1",road_status:"IMPASSABLE"}],warning_hazards:[],evidence:{}};const destination={store_number:"5537",store_name:"Test",city:"BKK",latitude:13,longitude:100,status:"active"};render(<RouteCard route={route} destination={destination}/>);expect(screen.getByRole("alert")).toHaveTextContent("ไม่พบเส้นทางที่หลีกเลี่ยงจุดปิดถนนทั้งหมด");expect(screen.getByText(/ยังพบจุดปิดถนน 1 จุด/)).toBeInTheDocument();expect(screen.getByText(/202609280016/)).toHaveTextContent("IMPASSABLE");expect(screen.queryByRole("link",{name:"นำทางด้วย Google Maps"})).not.toBeInTheDocument();expect(screen.getByText("ไม่เปิดการนำทางสำหรับสถานะนี้")).toHaveAttribute("aria-disabled","true")});
 it("describes safe, warning, and unverified route results factually",()=>{const destination={store_number:"1",store_name:"Test",city:"BKK",latitude:13,longitude:100,status:"active"};const base={route_id:null,origin_type:"DC" as const,origin_code:"D",destination_code:"1",vehicle_profile:"4W",distance_km:1,duration_minutes:2,route_geometry:{type:"LineString" as const,coordinates:[]},routing_provider:"VALHALLA",calculated_at:"2026-10-05",avoidance_attempted:false,blocking_hazards:[],warning_hazards:[],evidence:{}};const {rerender}=render(<RouteCard route={{...base,safety_state:"SAFE"}} destination={destination}/>);expect(screen.getByText("ไม่พบจุดปิดกั้นบนเส้นทางจากข้อมูลที่ตรวจสอบ")).toBeInTheDocument();rerender(<RouteCard route={{...base,safety_state:"WARNING"}} destination={destination}/>);expect(screen.getByText(/ไม่พบจุดปิดกั้นคงเหลือ/)).toBeInTheDocument();rerender(<RouteCard route={{...base,safety_state:"UNVERIFIED"}} destination={destination}/>);expect(screen.getByText(/^การตรวจสอบเส้นทางยังไม่ครบถ้วน$/)).toBeInTheDocument();expect(screen.queryByRole("link",{name:"นำทางด้วย Google Maps"})).not.toBeInTheDocument();expect(screen.getByText("ไม่เปิดการนำทางสำหรับสถานะนี้")).toHaveAttribute("aria-disabled","true")});

});
