import {describe,expect,it} from "vitest";
import {googleMapsNavigationUrl,loadAllBranchSituations,mapLayerColors,matchesSearch,routeStyle,routeSituationLabels,situationColors,situationLabels} from "./operations";
describe("operations semantics",()=>{
 it("uses factual Thai labels without claiming safety",()=>{expect(situationLabels.NO_NEARBY_FLOOD).toContain("ยังไม่พบหลักฐาน");expect(routeSituationLabels.NO_DETECTED_ROUTE_IMPACT).not.toContain("ปลอดภัย")});
 it("searches branch and DC fields",()=>{expect(matchesSearch("10241",{store_number:"10241",store_name:"บางนา",city:"กรุงเทพฯ"})).toBe(true);expect(matchesSearch("bang",{dc_code:"DC-1",dc_name:"Bangkok DC"})).toBe(true);expect(matchesSearch("เชียงใหม่",{store_number:"1",city:"กรุงเทพฯ"})).toBe(false)});
 it("keeps map layer colors centralized",()=>{expect(mapLayerColors).toEqual({branches:situationColors.NO_NEARBY_FLOOD,dcs:"#073b5c",gistda:"#2caec4",hdms:"#d43227",reports:"#e7a923",route:"#71808b"})});
 it("maps every route safety state to an operator-visible style",()=>{expect(routeStyle("SAFE")).toEqual({color:"#238b57",weight:6});expect(routeStyle("WARNING").color).toBe("#ed8a1c");expect(routeStyle("BLOCKED")).toMatchObject({color:"#d43227",dashArray:"12 8"});expect(routeStyle("UNVERIFIED")).toMatchObject({color:"#71808b",dashArray:"8 8"})});
 it("loads 2,574 situations in exactly three finite pages",async()=>{const offsets:number[]=[];const item={store_number:"1"} as never;const summary={} as never;const result=await loadAllBranchSituations(async offset=>{offsets.push(offset);return {summary,items:Array(Math.min(1000,2574-offset)).fill(item)}});expect(offsets).toEqual([0,1000,2000]);expect(result.items).toHaveLength(2574)});
 it("gates navigation and lets Maps refresh current location",()=>{const destination={store_number:"1",store_name:"B",city:"BKK",latitude:13.8,longitude:100.6,status:"active"};const base={route_id:null,origin_type:"CURRENT_LOCATION" as const,origin_code:"CURRENT",destination_code:"1",vehicle_profile:"4W",distance_km:1,duration_minutes:2,route_geometry:{type:"LineString" as const,coordinates:[[100.5,13.7],[100.6,13.8]]},routing_provider:"VALHALLA",calculated_at:"2026-01-01",navigation_waypoints:[[100.55,13.75]]};const url=googleMapsNavigationUrl({...base,safety_state:"SAFE"},undefined,destination)!;expect(url).not.toContain("origin=");expect(decodeURIComponent(url)).toContain("waypoints=13.75,100.55");expect(googleMapsNavigationUrl({...base,safety_state:"BLOCKED"},undefined,destination)).toBeNull();expect(googleMapsNavigationUrl({...base,safety_state:"UNVERIFIED"},undefined,destination)).toBeNull()});
});
